src/index.ts

##Description
vite HMR builds add a t=____ string to the end of marko files that was failing to match the original regex. so, I added a second one.
HMR refreshes in vite would kill the page until the server was restarted
- [n/a] I have updated/added documentation affected by my changes.

second regex capture to grab hmr rendered marko files

---

src/index.ts

Updates the compiler options to always pass the `resolveVirtualDependencies` config option.
Previously It was not passed for SSR compilation.
In the future this option may be used to enable native css module support within Marko templates and other features.

fix: always pass resolveVirtualDependencies compiler option

---

src/render-assets-transform.ts

refactor: use internal _vite tag instead of generating code to call __viteRenderAssets

---

src/render-assets-transform.ts

Reverts #16 since it ultimately causes all assets to be injected before any html has been rendered.

fix: revert #16

---

.changeset/unlucky-dogs-tap.md
src/index.ts

Avoid using fs readFile for browser entry. This allows virtual files to be browser entries.

fix: avoid fs readFile call for browser entry file sources

---

.changeset/little-rivers-jog.md
src/index.ts

Vite's `.load` api in the plugin context seems to have issues. Specifically it was found that when using the Marko plugin with many entry Marko files that it would break when using the `load` api.
Instead this PR saves the entry files sources along with the rest of the server manifest and uses that.

fix: avoid using Vite's load api

---

.changeset/warm-guests-carry.md
src/index.ts

The Vite config plugin hook exposes two apis. You can either mutate the provided config, or return a new config that is deep merged.
For some reason we were doing both which may have been leading to some issues.
This PR updates the code in that plugin hook to only use the mutation style api.

fix: switch to mutation style for vite config mutations

---

.changeset/dull-candles-brake.md
README.md
src/__tests__/fixtures/isomorphic-memory-store/__snapshots__/build.expected.loading.0.html
src/__tests__/fixtures/isomorphic-memory-store/__snapshots__/build.expected.loading.1.html
src/__tests__/fixtures/isomorphic-memory-store/__snapshots__/build.expected.step-0.0.html
src/__tests__/fixtures/isomorphic-memory-store/__snapshots__/dev.expected.loading.0.html
src/__tests__/fixtures/isomorphic-memory-store/__snapshots__/dev.expected.loading.1.html
src/__tests__/fixtures/isomorphic-memory-store/__snapshots__/dev.expected.step-0.0.html
src/__tests__/fixtures/isomorphic-memory-store/dev-server.js
src/__tests__/fixtures/isomorphic-memory-store/server.js
src/__tests__/fixtures/isomorphic-memory-store/src/components/class-component.marko
src/__tests__/fixtures/isomorphic-memory-store/src/components/implicit-component.marko
src/__tests__/fixtures/isomorphic-memory-store/src/components/layout-component.marko
src/__tests__/fixtures/isomorphic-memory-store/src/index.js
src/__tests__/fixtures/isomorphic-memory-store/src/template.marko
src/__tests__/fixtures/isomorphic-memory-store/test.config.ts
src/__tests__/main.test.ts
src/index.ts
src/store/__tests__/file-store.test.ts
src/store/__tests__/memory-store.test.ts
src/store/file-store.ts
src/store/index.ts
src/store/memory-store.ts
src/store/types.ts

Adds `store` option which allow specifying a method to preserve data between SSR and client builds. Provides two implementations: file system (default) and in memory.
Various data is produced during the SSR build which is necessary for the client build in linked mode. Today this is written to the file system. This PR decouples this logic into a store interface which can be implemented in any way. By default the store will continue to use the file system but an alternative in memory store is also provided which can improve performance when using Vite programatically.

feat: Add store option for linked mode builds

---

.changeset/grumpy-books-add.md
src/index.ts

Our unique virtual file paths did not properly encode the virtual file. This led vite to incorrectly resolve relative references within virtual files (eg inline stylesheets).
Resolves #53

fix: resolving assets from virtual files

---

.changeset/olive-panthers-deliver.md
src/__tests__/fixtures/isomorphic-commonjs/__snapshots__/build.expected.loading.0.html
src/__tests__/fixtures/isomorphic-commonjs/__snapshots__/build.expected.loading.1.html
src/__tests__/fixtures/isomorphic-commonjs/__snapshots__/build.expected.step-0.0.html
src/__tests__/fixtures/isomorphic-commonjs/__snapshots__/dev.expected.loading.0.html
src/__tests__/fixtures/isomorphic-commonjs/__snapshots__/dev.expected.loading.1.html
src/__tests__/fixtures/isomorphic-commonjs/__snapshots__/dev.expected.step-0.0.html
src/__tests__/fixtures/isomorphic-commonjs/dev-server.js
src/__tests__/fixtures/isomorphic-commonjs/node_modules/test-package/common/html-attributes/index.js
src/__tests__/fixtures/isomorphic-commonjs/node_modules/test-package/components/test-button/component-browser.js
src/__tests__/fixtures/isomorphic-commonjs/node_modules/test-package/components/test-button/index.marko
src/__tests__/fixtures/isomorphic-commonjs/node_modules/test-package/components/test-button/marko-tag.json
src/__tests__/fixtures/isomorphic-commonjs/node_modules/test-package/marko.json
src/__tests__/fixtures/isomorphic-commonjs/node_modules/test-package/package.json
src/__tests__/fixtures/isomorphic-commonjs/node_modules/test-package/test-button.browser.json
src/__tests__/fixtures/isomorphic-commonjs/package.json
src/__tests__/fixtures/isomorphic-commonjs/server.js
src/__tests__/fixtures/isomorphic-commonjs/src/components/class-component.marko
src/__tests__/fixtures/isomorphic-commonjs/src/components/implicit-component.marko
src/__tests__/fixtures/isomorphic-commonjs/src/components/layout-component.marko
src/__tests__/fixtures/isomorphic-commonjs/src/index.js
src/__tests__/fixtures/isomorphic-commonjs/src/template.marko
src/__tests__/fixtures/isomorphic-commonjs/test.config.ts
src/index.ts

In dev mode, .marko files with CommonJS dependencies will fail in SSR because Vite loads them in ESM context.
This PR attempts to handle this case by wrapping them in module that requires it using `createRequire`. This causes the marko file to be loaded using Marko's require hook in a CommonJS context.
- The mechanism is only used in dev
- A heuristic is used to test if the module is likely CommonJS and only these files are wrapped

fix: cjs imports from marko files in dev

---

.changeset/wet-parents-occur.md
src/__tests__/fixtures/isomorphic-runtime-base-path/test.config.ts
src/components/vite.marko

The script which sets the optional runtime base path for resources was being rendered before the doctype declaration. This change ensures the script is rendered right before the JS asset scripts are written.

fix: base path script in head or body when present

---

.changeset/pretty-plums-perform.md
src/index.ts

Ensure `browser` export condition is configured when in `test` mode and targeting a dom environment.
Workaround for https://github.com/vitest-dev/vitest/issues/2603 which causes the incorrect Marko runtime to be loaded in the brower env for that test runner.

fix: ensure proper resolve condition set for vitest env

---

.changeset/fair-peas-impress.md
src/index.ts

Fixes a regression where SSR Marko files were not being bundled in `build` mode.

fix: ssr bundled Marko files in build mode

---

src/__tests__/main.test.ts

Make `testPage` function to accept `http.Server | Http2SecureServer` instead of `http.Server`.
This PR fixes the type incompatibility with Vite 5.
related: https://github.com/vitejs/vite/pull/14834

test: change server type for vite 5 change

---

.changeset/sharp-guests-know.md
README.md
package-lock.json
package.json
src/__tests__/fixtures/isomorphic-relative-asset-import/__snapshots__/build.expected.loading.0.html
src/__tests__/fixtures/isomorphic-relative-asset-import/__snapshots__/build.expected.loading.1.html
src/__tests__/fixtures/isomorphic-relative-asset-import/__snapshots__/build.expected.step-0.0.html
src/__tests__/fixtures/isomorphic-relative-asset-import/__snapshots__/dev.expected.loading.0.html
src/__tests__/fixtures/isomorphic-relative-asset-import/__snapshots__/dev.expected.loading.1.html
src/__tests__/fixtures/isomorphic-relative-asset-import/__snapshots__/dev.expected.step-0.0.html
src/__tests__/fixtures/isomorphic-relative-asset-import/dev-server.mjs
src/__tests__/fixtures/isomorphic-relative-asset-import/server.mjs
src/__tests__/fixtures/isomorphic-relative-asset-import/src/components/class-component.marko
src/__tests__/fixtures/isomorphic-relative-asset-import/src/components/implicit-component.marko
src/__tests__/fixtures/isomorphic-relative-asset-import/src/components/layout-component.marko
src/__tests__/fixtures/isomorphic-relative-asset-import/src/components/logo.svg
src/__tests__/fixtures/isomorphic-relative-asset-import/src/index.js
src/__tests__/fixtures/isomorphic-relative-asset-import/src/template.marko
src/__tests__/fixtures/isomorphic-relative-asset-import/test.config.ts
src/__tests__/main.test.ts
src/index.ts
src/relative-assets-transform.ts

Brings over the (adapted) native tag relative asset import transform from @marko/run.
This allows you to have code like `<img src="./relative-path.png">` be processed with vite.

feat: relative assets transform

---

.changeset/weak-bulldogs-perform.md
src/index.ts

Fix issue where filename from vites watcher was not in posix which was preventing clearing cached data.
resolves #75

fix: normalize windows paths in vites watcher

---

.changeset/rude-roses-draw.md
src/index.ts

Avoids matching `~/` with our resolve alias.
Somewhat of a workaround for #133.

fix: improve resolve alias with ~

---

.changeset/soft-fireants-burn.md
src/index.ts

Stackblitz Web Containers do not support loading native addons. Our CJS to ESM transform code relies on `@parcel/source-maps` which loads native addons. This change makes loading this package conditional and on-demand to prevent runtime failures when CJS transformations are not needed.

fix: native addons failure in stackblitz

---

.changeset/silent-sheep-admire.md
src/render-assets-runtime.ts

Fix a bug since @marko/vite@4.1.14, whereby Content-Security-Policies errors are thrown when `$global.cspNonce` is used.

fix: broken vite preload when used with cspnonce

---

src/__tests__/fixtures/isomorphic-base-url/dev-server.mjs
src/__tests__/fixtures/isomorphic-basic/dev-server.mjs
src/__tests__/fixtures/isomorphic-bundle-splitting/dev-server.mjs
src/__tests__/fixtures/isomorphic-circular-entry-file/dev-server.mjs
src/__tests__/fixtures/isomorphic-commonjs-dir-import/dev-server.mjs
src/__tests__/fixtures/isomorphic-commonjs-svg/dev-server.mjs
src/__tests__/fixtures/isomorphic-commonjs/dev-server.mjs
src/__tests__/fixtures/isomorphic-css-loader-import/dev-server.mjs
src/__tests__/fixtures/isomorphic-glob-import/dev-server.mjs
src/__tests__/fixtures/isomorphic-marko-dep/dev-server.mjs
src/__tests__/fixtures/isomorphic-modulepreload/dev-server.mjs
src/__tests__/fixtures/isomorphic-relative-asset-import/dev-server.mjs
src/__tests__/fixtures/isomorphic-runtime-base-path/dev-server.mjs

This PR fixes ecosystem-ci with Vite v6 beta by setting `build.assetsInlineLimit: 0` for SSR tests in dev.
Vite 6 now inlines SVG files even in dev that will be inlined for build (https://github.com/vitejs/vite/pull/18581).
That caused the snapshot to change and made the ecosystem-ci to fail.
Because `build.assetsInlineLimit: 0` was set for SSR test in build, I set them in dev as well to make the ecosystem-ci pass.

chore: set `build.assetsInlineLimit: 0` for SSR tests in dev

---

.changeset/five-schools-complain.md
src/index.ts

fix: load translator with require when checking tags API

---

.changeset/serious-zebras-tell.md
src/index.ts

Vite detects if file is CSS module though `.module.css` file ending, while using `extname` only keeps `.css`.
Use `encodeURIComponent` instead as it seems better than reimplementing part of the Vites detection logic.
`query` before: `?marko-virtual&id=Li91c2VyLiRpZCtwYWdlLm1hcmtvLm1vZHVsZS5jc3M.css`
`query` after: `?marko-virtual&id=.%2Fuser.%24id%2Bpage.marko.module.css`
Probably should add tests for this too, but I haven't done that.

feat: support css modules

---

.changeset/strange-tomatoes-buy.md
src/index.ts

Update `options.input` in `options` hook instead of `buildStart` hook.
[`options` hook](https://rollupjs.org/plugin-development/#options) is the recommended hook to update the options. `buildStart` hook is not meant to be used to update the option. In addition, rolldown does not allow updating the option in `buildStart` hook.
Without this PR, this plugin does not work with Rolldown powered Vite. But with this PR, the tests passes 🙂

fix: update options.input in options hook

---

.changeset/afraid-impalas-fetch.md
src/__tests__/fixtures/isomorphic-custom-entries/src/other.marko
src/render-assets-transform.ts

Makes the vite injection script optional to support `<head>` and `<body>` tags used in non-entry templates.

fix: optional vite asset inject to support non-entry templates
